FROM python:3.14-slim

ENV PYTHONPATH="/app:/app"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends git ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock README.md ./

RUN pip install --no-cache-dir poetry
RUN poetry config virtualenvs.create false

COPY . .

RUN poetry install --only main --no-interaction --no-ansi

EXPOSE 5006
