[project]
name = "software-metrics-machine"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pandas (>=2.3.2,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "matplotlib (>=3.10.5,<4.0.0)",
    "networkx (>=3.5,<4.0)",
    "jq (>=1.10.0,<2.0.0)",
    "panel (>=1.8.0,<2.0.0)",
    "click (>=8.3.0,<9.0.0)",
    "squarify (>=0.4.4,<0.5.0)",
    "fastapi[standard] (>=0.117.1,<0.118.0)",
    "ipywidgets (>=8.1.7,<9.0.0)",
    "langchain (>=0.3.27,<0.4.0)",
    "langchain-community (>=0.3.31,<0.4.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.3.0"
black = "^25.1.0"
flake8 = "^7.3.0"
isort = "^6.0.1"
pytest = "^8.4.2"
watchfiles = "^1.1.0"
pydantic = "^2.11.9"
pytest-cov = "^7.0.0"

