sonar.projectKey=marabesi_software-metrics-machine
sonar.organization=marabesi
sonar.coverage.exclusions=**/__tests__/**,**/__mocks__/**,**/node_modules/**,**/dist/**,**/coverage/**,**/src/**/*.d.ts,**/cypress/**