FROM node:25-slim

RUN apt-get update \
	&& apt-get install -y --no-install-recommends git \
	&& rm -rf /var/lib/apt/lists/*

RUN	git config --global --add safe.directory /app/react

WORKDIR /tmp/smm-install-test

ARG PACKED_FILE

COPY ${PACKED_FILE} /tmp/package.tgz

# installing given package to check if it can be installed without errors
RUN npm i -g /tmp/package.tgz
