# syntax = docker/dockerfile:1

FROM node:22-slim AS base

ARG PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app

# Dependencies
FROM base AS dependencies
COPY package.json package-lock.json ./
RUN npm i

COPY . .
