name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "docs/**"

jobs:
  build-typescript:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: ./envvars.for.actions

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Set env variables
        run: cp apps/webapp/.env.local.example apps/webapp/.env

      - name: Install dependencies
        run: pnpm install

      - name: Build workspace
        run: pnpm run build
